// <auto-generated />
using System;
using E_CODING_DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_CODING_DAL.Migrations
{
    [DbContext(typeof(TemplateProjectDbContext))]
    [Migration("20231229142142_AddingEFExtensions")]
    partial class AddingEFExtensions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("E_CODING_DAL.Models.TechniqueParameter", b =>
                {
                    b.Property<int>("TechniqueParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechniqueParameterId"), 1L, 1);

                    b.Property<string>("TechniqueParameterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechniqueParameterValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TemplateTechniqueId")
                        .HasColumnType("int");

                    b.HasKey("TechniqueParameterId");

                    b.HasIndex("TemplateTechniqueId");

                    b.ToTable("TechniqueParameter");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateProject", b =>
                {
                    b.Property<int>("TemplateProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateProjectId"), 1L, 1);

                    b.Property<string>("TemplateProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateProjectTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateProjectVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateProjectVersionNet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TemplateSolutionId")
                        .HasColumnType("int");

                    b.HasKey("TemplateProjectId");

                    b.HasIndex("TemplateSolutionId");

                    b.ToTable("TemplateProject");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateResult", b =>
                {
                    b.Property<int>("TemplateResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateResultId"), 1L, 1);

                    b.Property<int?>("TemplateProjectId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateResultDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateResultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateResultTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateResultVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateResultVersionNET")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateResultId");

                    b.HasIndex("TemplateProjectId");

                    b.ToTable("TemplateResult");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateResultItem", b =>
                {
                    b.Property<int>("TemplateResultItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateResultItemId"), 1L, 1);

                    b.Property<int>("TemplateFonctionnelId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateResultFinalContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TemplateResultId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateResultInitialContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateResultItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateResultItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateResultItemTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateResultItemVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateResultItemVersionNET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateTechniqueId")
                        .HasColumnType("int");

                    b.HasKey("TemplateResultItemId");

                    b.HasIndex("TemplateResultId");

                    b.ToTable("TemplateResultItem");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateSolution", b =>
                {
                    b.Property<int>("TemplateSolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateSolutionId"), 1L, 1);

                    b.Property<int>("TemplateProjectId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateSolutionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateSolutionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateSolutionTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateSolutionVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateSolutionVersionNet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateSolutionId");

                    b.ToTable("TemplateSolution");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateTechnique", b =>
                {
                    b.Property<int>("TemplateTechniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateTechniqueId"), 1L, 1);

                    b.Property<int?>("TemplateProjectId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateTechniqueDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateTechniqueName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateTechniqueTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateTechniqueVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateTechniqueVersionNET")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateTechniqueId");

                    b.HasIndex("TemplateProjectId");

                    b.ToTable("TemplateTechnique");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateTechniqueItem", b =>
                {
                    b.Property<int>("TemplateTechniqueItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateTechniqueItemId"), 1L, 1);

                    b.Property<string>("TemplateTechniqueFinalContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TemplateTechniqueId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateTechniqueInitialFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateTechniqueItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateTechniqueItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateTechniqueItemTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateTechniqueItemVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateTechniqueItemVersionNET")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateTechniqueItemId");

                    b.HasIndex("TemplateTechniqueId");

                    b.ToTable("TemplateTechniqueItem");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TechniqueParameter", b =>
                {
                    b.HasOne("E_CODING_DAL.Models.TemplateTechnique", "TemplateTechnique")
                        .WithMany("TechniqueParameter")
                        .HasForeignKey("TemplateTechniqueId");

                    b.Navigation("TemplateTechnique");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateProject", b =>
                {
                    b.HasOne("E_CODING_DAL.Models.TemplateSolution", "TemplateSolution")
                        .WithMany("TemplateProject")
                        .HasForeignKey("TemplateSolutionId");

                    b.Navigation("TemplateSolution");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateResult", b =>
                {
                    b.HasOne("E_CODING_DAL.Models.TemplateProject", null)
                        .WithMany("TemplateResult")
                        .HasForeignKey("TemplateProjectId");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateResultItem", b =>
                {
                    b.HasOne("E_CODING_DAL.Models.TemplateResult", "TemplateResult")
                        .WithMany("TemplateResultItem")
                        .HasForeignKey("TemplateResultId");

                    b.Navigation("TemplateResult");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateTechnique", b =>
                {
                    b.HasOne("E_CODING_DAL.Models.TemplateProject", "TemplateProject")
                        .WithMany("TemplateTechnique")
                        .HasForeignKey("TemplateProjectId");

                    b.Navigation("TemplateProject");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateTechniqueItem", b =>
                {
                    b.HasOne("E_CODING_DAL.Models.TemplateTechnique", "TemplateTechnique")
                        .WithMany("TemplateTechniqueItem")
                        .HasForeignKey("TemplateTechniqueId");

                    b.Navigation("TemplateTechnique");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateProject", b =>
                {
                    b.Navigation("TemplateResult");

                    b.Navigation("TemplateTechnique");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateResult", b =>
                {
                    b.Navigation("TemplateResultItem");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateSolution", b =>
                {
                    b.Navigation("TemplateProject");
                });

            modelBuilder.Entity("E_CODING_DAL.Models.TemplateTechnique", b =>
                {
                    b.Navigation("TechniqueParameter");

                    b.Navigation("TemplateTechniqueItem");
                });
#pragma warning restore 612, 618
        }
    }
}
